apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: bindian0509/k8s-net-users
          resources:
            requests:
              memory: "512Mi"
              cpu: "900m"
            limits:
              memory: "512Mi"
              cpu: "900m"
